### ISSUE TITLE
ModuleNotFoundError: No module named 'openood.pipelines.train_fsood_pipeline'

### ISSUE THREAD

**Issue by yimuwangcs** [YBZh/OpenOOD-VLM#1]
Hi,

Thank you again for the amazing paper and codes. I was trying to run the training code but encountered the following errors. I would appreciate it if you could provide it. Thanks.

`ModuleNotFoundError: No module named 'openood.pipelines.train_fsood_pipeline'`

Best,
Yimu

**Comment by YBZh** [comment]
Thanks for your interest. The required file is updated.
