### ISSUE TITLE
No such file or directory: './data/benchmark_imglist/imagenet/train_imagenet_idood_last1k_syn2.txt'

### ISSUE THREAD

**Issue by WNJXYK** [YBZh/OpenOOD-VLM#3]
Hello! I greatly appreciate your excellent work. 
However, I've encountered an error while attempting to reproduce your results.

```plain
FileNotFoundError: [Errno 2] No such file or directory: './data/benchmark_imglist/imagenet/train_imagenet_idood_last1k_syn2.txt'
FileNotFoundError: [Errno 2] No such file or directory: './data/benchmark_imglist/cifar100/test_cifar100_full.txt'
```

It seems that the dataset files named "train_imagenet_idood_last1k_syn2.txt" and "test_cifar100_full.txt" are missing. I wonder if you can provide the file. Thanks!

**Comment by YBZh** [comment]
Thanks for your interest. The 'train_imagenet_idood_last1k_syn2.txt' is only used in the model training of the LAPT model; you can delete this line in the testing stage. The 'test_cifar100_full.txt' contains the test data of the CIFAR-100 dataset, which should be generated by yourself (it's very easy, just put every image file path on one line).

**Comment by WNJXYK** [comment]
Okay. Thank you.
