### ISSUE TITLE
The file "./data/benchmark_imglist/imagenet/train_imagenet_idood_last1k_syn2.txt" and the path "/home/notebook/code/personal/S9052995/syn_image/ImageNet_sdxl_ood_32/guidance_scale7.5/" cannot be found.

### ISSUE THREAD

**Issue by shuolucs** [YBZh/OpenOOD-VLM#6]
Hey there!

I just wanted to say that your work LAPT is really impressive. I'm trying to retrain it, but I'm running into a bit of trouble. I'm getting this error: "No such file or directory: './data/benchmark_imglist/imagenet/train_imagenet_idood_last1k_syn2.txt' and "/home/notebook/code/personal/S9052995/syn_image/ImageNet_sdxl_ood_32/guidance_scale7.5/" .

I was wondering if you could point me in the right direction to find this file or give me a hint on how to recreate it? It would be a huge help in getting LAPT up and running.

Thanks a bunch! Looking forward to your reply.

**Comment by YBZh** [comment]
Thanks for your interest. The required datasets are stored on the company's server, and sharing them is quite troublesome. However, you can easily recreate it by yourself. The details are described in the paper. Specifically, for the synthetic images, I used SDXL as the text-to-image generator, and generated diverse images by using different seeds. For the retrieved real images, I used the class name to search for the nearest images from a 60M subset of the Laion400M dataset.
